### ISSUE TITLE
Add WalletConnect functionality

### ISSUE THREAD

**Issue by TheMoneyLisa** [decentri-fi/showcase#8]
In order to successfully use decentrifi with wallets and tools like [Coinshift](https://coinshift.xyz/), we need walletconnect integration.

## Allow it as an option for basic transactions

We need basic fetching of accounts, as well as transaction execution, just like we have with browser-injection.

## Allow it as an option for SiWe

Sign in with ethereum currently only uses the underlying metamask/browser injection. Support WalletConnect here too.

**Comment by Qkyrie** [comment]
wallet connected added
